export interface Surah {
  id: number;
  name_ar: string;
  name_sq: string;
  total_ayahs: number;
  start_page: number;
  end_page: number;
}

export const QURAN_SURAHS: Surah[] = [
  { id: 1, name_ar: "الفاتحة", name_sq: "El-Fatiha", total_ayahs: 7, start_page: 1, end_page: 1 },
  { id: 2, name_ar: "البقرة", name_sq: "El-Bekare", total_ayahs: 286, start_page: 2, end_page: 49 },
  { id: 3, name_ar: "آل عمران", name_sq: "Ali Imran", total_ayahs: 200, start_page: 50, end_page: 76 },
  { id: 4, name_ar: "النساء", name_sq: "En-Nisa", total_ayahs: 176, start_page: 77, end_page: 106 },
  { id: 5, name_ar: "المائدة", name_sq: "El-Maide", total_ayahs: 120, start_page: 106, end_page: 127 },
  { id: 6, name_ar: "الأنعام", name_sq: "El-En'am", total_ayahs: 165, start_page: 128, end_page: 150 },
  { id: 7, name_ar: "الأعراف", name_sq: "El-A'raf", total_ayahs: 206, start_page: 151, end_page: 176 },
  { id: 8, name_ar: "الأنفال", name_sq: "El-Enfal", total_ayahs: 75, start_page: 177, end_page: 186 },
  { id: 9, name_ar: "التوبة", name_sq: "Et-Teube", total_ayahs: 129, start_page: 187, end_page: 207 },
  { id: 10, name_ar: "يونس", name_sq: "Junus", total_ayahs: 109, start_page: 208, end_page: 221 },
  { id: 11, name_ar: "هود", name_sq: "Hud", total_ayahs: 123, start_page: 221, end_page: 235 },
  { id: 12, name_ar: "يوسف", name_sq: "Jusuf", total_ayahs: 111, start_page: 235, end_page: 248 },
  { id: 13, name_ar: "الرعد", name_sq: "Er-Rra'd", total_ayahs: 43, start_page: 249, end_page: 255 },
  { id: 14, name_ar: "إبراهيم", name_sq: "Ibrahim", total_ayahs: 52, start_page: 255, end_page: 261 },
  { id: 15, name_ar: "الحجر", name_sq: "El-Hixhr", total_ayahs: 99, start_page: 262, end_page: 267 },
  { id: 16, name_ar: "النحل", name_sq: "En-Nahl", total_ayahs: 128, start_page: 267, end_page: 281 },
  { id: 17, name_ar: "الإسراء", name_sq: "El-Isra", total_ayahs: 111, start_page: 282, end_page: 293 },
  { id: 18, name_ar: "الكهف", name_sq: "El-Kehf", total_ayahs: 110, start_page: 293, end_page: 304 },
  { id: 19, name_ar: "مريم", name_sq: "Merjem", total_ayahs: 98, start_page: 305, end_page: 312 },
  { id: 20, name_ar: "طه", name_sq: "Ta Ha", total_ayahs: 135, start_page: 312, end_page: 321 },
  { id: 21, name_ar: "الأنبياء", name_sq: "El-Enbija", total_ayahs: 112, start_page: 322, end_page: 331 },
  { id: 22, name_ar: "الحج", name_sq: "El-Haxh", total_ayahs: 78, start_page: 332, end_page: 341 },
  { id: 23, name_ar: "المؤمنون", name_sq: "El-Mu'minun", total_ayahs: 118, start_page: 342, end_page: 349 },
  { id: 24, name_ar: "النور", name_sq: "En-Nur", total_ayahs: 64, start_page: 350, end_page: 359 },
  { id: 25, name_ar: "الفرقان", name_sq: "El-Furkan", total_ayahs: 77, start_page: 359, end_page: 366 },
  { id: 26, name_ar: "الشعراء", name_sq: "Esh-Shuara", total_ayahs: 227, start_page: 367, end_page: 376 },
  { id: 27, name_ar: "النمل", name_sq: "En-Neml", total_ayahs: 93, start_page: 377, end_page: 385 },
  { id: 28, name_ar: "القصص", name_sq: "El-Kasas", total_ayahs: 88, start_page: 385, end_page: 396 },
  { id: 29, name_ar: "العنكبوت", name_sq: "El-Ankebut", total_ayahs: 69, start_page: 396, end_page: 404 },
  { id: 30, name_ar: "الروم", name_sq: "Er-Rrum", total_ayahs: 60, start_page: 404, end_page: 410 },
  { id: 31, name_ar: "لقمان", name_sq: "Llukman", total_ayahs: 34, start_page: 411, end_page: 414 },
  { id: 32, name_ar: "السجدة", name_sq: "Es-Sexhde", total_ayahs: 30, start_page: 415, end_page: 417 },
  { id: 33, name_ar: "الأحزاب", name_sq: "El-Ahzab", total_ayahs: 73, start_page: 418, end_page: 427 },
  { id: 34, name_ar: "سبأ", name_sq: "Sebe'", total_ayahs: 54, start_page: 428, end_page: 434 },
  { id: 35, name_ar: "فاطر", name_sq: "Fatir", total_ayahs: 45, start_page: 434, end_page: 440 },
  { id: 36, name_ar: "يس", name_sq: "Ja Sin", total_ayahs: 83, start_page: 440, end_page: 445 },
  { id: 37, name_ar: "الصافات", name_sq: "Es-Saffat", total_ayahs: 182, start_page: 446, end_page: 452 },
  { id: 38, name_ar: "ص", name_sq: "Sad", total_ayahs: 88, start_page: 453, end_page: 458 },
  { id: 39, name_ar: "الزمر", name_sq: "Ez-Zumer", total_ayahs: 75, start_page: 458, end_page: 467 },
  { id: 40, name_ar: "غافر", name_sq: "Gafir", total_ayahs: 85, start_page: 467, end_page: 476 },
  { id: 41, name_ar: "فصلت", name_sq: "Fussilet", total_ayahs: 54, start_page: 477, end_page: 482 },
  { id: 42, name_ar: "الشورى", name_sq: "Esh-Shura", total_ayahs: 53, start_page: 483, end_page: 489 },
  { id: 43, name_ar: "الزخرف", name_sq: "Ez-Zuhruf", total_ayahs: 89, start_page: 489, end_page: 495 },
  { id: 44, name_ar: "الدخان", name_sq: "Ed-Duhan", total_ayahs: 59, start_page: 496, end_page: 498 },
  { id: 45, name_ar: "الجاثية", name_sq: "El-Xhathije", total_ayahs: 37, start_page: 499, end_page: 502 },
  { id: 46, name_ar: "الأحقاف", name_sq: "El-Ahkaf", total_ayahs: 35, start_page: 502, end_page: 506 },
  { id: 47, name_ar: "محمد", name_sq: "Muhamed", total_ayahs: 38, start_page: 507, end_page: 510 },
  { id: 48, name_ar: "الفتح", name_sq: "El-Fet'h", total_ayahs: 29, start_page: 511, end_page: 515 },
  { id: 49, name_ar: "الحجرات", name_sq: "El-Huxhurat", total_ayahs: 18, start_page: 515, end_page: 517 },
  { id: 50, name_ar: "ق", name_sq: "Kaf", total_ayahs: 45, start_page: 518, end_page: 520 },
  { id: 51, name_ar: "الذاريات", name_sq: "Edh-Dharijat", total_ayahs: 60, start_page: 520, end_page: 523 },
  { id: 52, name_ar: "الطور", name_sq: "Et-Tur", total_ayahs: 49, start_page: 523, end_page: 525 },
  { id: 53, name_ar: "النجم", name_sq: "En-Nexhm", total_ayahs: 62, start_page: 526, end_page: 528 },
  { id: 54, name_ar: "القمر", name_sq: "El-Kamer", total_ayahs: 55, start_page: 528, end_page: 531 },
  { id: 55, name_ar: "الرحمن", name_sq: "Er-Rrahman", total_ayahs: 78, start_page: 531, end_page: 534 },
  { id: 56, name_ar: "الواقعة", name_sq: "El-Vakia", total_ayahs: 96, start_page: 534, end_page: 537 },
  { id: 57, name_ar: "الحديد", name_sq: "El-Hadid", total_ayahs: 29, start_page: 537, end_page: 541 },
  { id: 58, name_ar: "المجادلة", name_sq: "El-Muxhadele", total_ayahs: 22, start_page: 542, end_page: 545 },
  { id: 59, name_ar: "الحشر", name_sq: "El-Hashr", total_ayahs: 24, start_page: 545, end_page: 548 },
  { id: 60, name_ar: "الممتحنة", name_sq: "El-Mumtehine", total_ayahs: 13, start_page: 549, end_page: 551 },
  { id: 61, name_ar: "الصف", name_sq: "Es-Saff", total_ayahs: 14, start_page: 551, end_page: 552 },
  { id: 62, name_ar: "الجمعة", name_sq: "El-Xhumu'a", total_ayahs: 11, start_page: 553, end_page: 554 },
  { id: 63, name_ar: "المنافقون", name_sq: "El-Munafikun", total_ayahs: 11, start_page: 554, end_page: 556 },
  { id: 64, name_ar: "التغابن", name_sq: "Et-Tegabun", total_ayahs: 18, start_page: 556, end_page: 557 },
  { id: 65, name_ar: "الطلاق", name_sq: "Et-Talak", total_ayahs: 12, start_page: 558, end_page: 559 },
  { id: 66, name_ar: "التحريم", name_sq: "Et-Tahrim", total_ayahs: 12, start_page: 560, end_page: 561 },
  { id: 67, name_ar: "الملك", name_sq: "El-Mulk", total_ayahs: 30, start_page: 562, end_page: 564 },
  { id: 68, name_ar: "القلم", name_sq: "El-Kalem", total_ayahs: 52, start_page: 564, end_page: 566 },
  { id: 69, name_ar: "الحاقة", name_sq: "El-Hakka", total_ayahs: 52, start_page: 566, end_page: 568 },
  { id: 70, name_ar: "المعارج", name_sq: "El-Mearixh", total_ayahs: 44, start_page: 568, end_page: 570 },
  { id: 71, name_ar: "نوح", name_sq: "Nuh", total_ayahs: 28, start_page: 570, end_page: 571 },
  { id: 72, name_ar: "الجن", name_sq: "El-Xhinn", total_ayahs: 28, start_page: 572, end_page: 573 },
  { id: 73, name_ar: "المزمل", name_sq: "El-Muzzemmil", total_ayahs: 20, start_page: 573, end_page: 575 },
  { id: 74, name_ar: "المدثر", name_sq: "El-Muddeth-thir", total_ayahs: 56, start_page: 575, end_page: 577 },
  { id: 75, name_ar: "القيامة", name_sq: "El-Kijame", total_ayahs: 40, start_page: 577, end_page: 578 },
  { id: 76, name_ar: "الإنسان", name_sq: "El-Insan", total_ayahs: 31, start_page: 578, end_page: 580 },
  { id: 77, name_ar: "المرسلات", name_sq: "El-Murselat", total_ayahs: 50, start_page: 580, end_page: 581 },
  { id: 78, name_ar: "النبأ", name_sq: "En-Nebe'", total_ayahs: 40, start_page: 582, end_page: 583 },
  { id: 79, name_ar: "النازعات", name_sq: "En-Nazi'at", total_ayahs: 46, start_page: 583, end_page: 584 },
  { id: 80, name_ar: "عبس", name_sq: "Abese", total_ayahs: 42, start_page: 585, end_page: 585 },
  { id: 81, name_ar: "التكوير", name_sq: "Et-Tekvir", total_ayahs: 29, start_page: 586, end_page: 586 },
  { id: 82, name_ar: "الانفطار", name_sq: "El-Infitar", total_ayahs: 19, start_page: 587, end_page: 587 },
  { id: 83, name_ar: "المطففين", name_sq: "El-Mutaffifin", total_ayahs: 36, start_page: 587, end_page: 589 },
  { id: 84, name_ar: "الانشقاق", name_sq: "El-Inshikak", total_ayahs: 25, start_page: 589, end_page: 589 },
  { id: 85, name_ar: "البروج", name_sq: "El-Buruxh", total_ayahs: 22, start_page: 590, end_page: 590 },
  { id: 86, name_ar: "الطارق", name_sq: "Et-Tarik", total_ayahs: 17, start_page: 591, end_page: 591 },
  { id: 87, name_ar: "الأعلى", name_sq: "El-A'la", total_ayahs: 19, start_page: 591, end_page: 592 },
  { id: 88, name_ar: "الغاشية", name_sq: "El-Gashije", total_ayahs: 26, start_page: 592, end_page: 592 },
  { id: 89, name_ar: "الفجر", name_sq: "El-Fexhr", total_ayahs: 30, start_page: 593, end_page: 594 },
  { id: 90, name_ar: "البلد", name_sq: "El-Beled", total_ayahs: 20, start_page: 594, end_page: 594 },
  { id: 91, name_ar: "الشمس", name_sq: "Esh-Shems", total_ayahs: 15, start_page: 595, end_page: 595 },
  { id: 92, name_ar: "الليل", name_sq: "El-Lejl", total_ayahs: 21, start_page: 595, end_page: 596 },
  { id: 93, name_ar: "الضحى", name_sq: "Ed-Duha", total_ayahs: 11, start_page: 596, end_page: 596 },
  { id: 94, name_ar: "الشرح", name_sq: "Esh-Sherh", total_ayahs: 8, start_page: 596, end_page: 596 },
  { id: 95, name_ar: "التين", name_sq: "Et-Tin", total_ayahs: 8, start_page: 597, end_page: 597 },
  { id: 96, name_ar: "العلق", name_sq: "El-Alak", total_ayahs: 19, start_page: 597, end_page: 597 },
  { id: 97, name_ar: "القدر", name_sq: "El-Kadr", total_ayahs: 5, start_page: 598, end_page: 598 },
  { id: 98, name_ar: "البينة", name_sq: "El-Bejjine", total_ayahs: 8, start_page: 598, end_page: 599 },
  { id: 99, name_ar: "الزلزلة", name_sq: "Ez-Zelzele", total_ayahs: 8, start_page: 599, end_page: 599 },
  { id: 100, name_ar: "العاديات", name_sq: "El-Adijat", total_ayahs: 11, start_page: 599, end_page: 600 },
  { id: 101, name_ar: "القارعة", name_sq: "El-Kari'a", total_ayahs: 11, start_page: 600, end_page: 600 },
  { id: 102, name_ar: "التكاثر", name_sq: "Et-Tekathur", total_ayahs: 8, start_page: 600, end_page: 600 },
  { id: 103, name_ar: "العصر", name_sq: "El-Asr", total_ayahs: 3, start_page: 601, end_page: 601 },
  { id: 104, name_ar: "الهمزة", name_sq: "El-Humeze", total_ayahs: 9, start_page: 601, end_page: 601 },
  { id: 105, name_ar: "الفيل", name_sq: "El-Fil", total_ayahs: 5, start_page: 601, end_page: 601 },
  { id: 106, name_ar: "قريش", name_sq: "Kurejsh", total_ayahs: 4, start_page: 602, end_page: 602 },
  { id: 107, name_ar: "الماعون", name_sq: "El-Ma'un", total_ayahs: 7, start_page: 602, end_page: 602 },
  { id: 108, name_ar: "الكوثر", name_sq: "El-Keuther", total_ayahs: 3, start_page: 602, end_page: 602 },
  { id: 109, name_ar: "الكافرون", name_sq: "El-Kafirun", total_ayahs: 6, start_page: 603, end_page: 603 },
  { id: 110, name_ar: "النصر", name_sq: "En-Nasr", total_ayahs: 3, start_page: 603, end_page: 603 },
  { id: 111, name_ar: "المسد", name_sq: "El-Mesed", total_ayahs: 5, start_page: 603, end_page: 603 },
  { id: 112, name_ar: "الإخلاص", name_sq: "El-Ihlas", total_ayahs: 4, start_page: 604, end_page: 604 },
  { id: 113, name_ar: "الفلق", name_sq: "El-Felek", total_ayahs: 5, start_page: 604, end_page: 604 },
  { id: 114, name_ar: "الناس", name_sq: "En-Nas", total_ayahs: 6, start_page: 604, end_page: 604 }
];
